Hw lesson12
Bakashev/TMS_HW pull request #1
Opened 2023-03-31 13:34 UTC by Bakashev

2023-03-31 14:36 UTC, vimoro requested changes

2023-03-31 14:36 UTC, vimoro commented on hw_lesson12.py
> +        return args, kwargs
вот тут нужно вызвать исходную функцию, иначе ты её вообще не выполняешь и соответственно не теряешь зрначение

2023-03-31 15:01 UTC, Bakashev commented on hw_lesson12.py
> +        return args, kwargs
Исправил

2023-04-03 13:30 UTC, vimoro approved these changes

2023-04-05 11:59 UTC, merged